spring:
  application:
    name: Hospital Management Application
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_SCHEMA:nbhdb}
    driverClassName: org.postgresql.Driver
    username: ${PG_USERNAME:nbhdbadmin}
    password: ${PG_PASSWD:SkyDreamer@2024}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /hosp-mgmt

logging.level:
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE