spring:
  application:
    name: Hospital Management Application
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true

server:
  port: 8080
  servlet:
    context-path: /hosp-mgmt

logging.level:
  org.hibernate: TRACE