spring:
  application:
    name: Hospital Management Application
  datasource:
    url: jdbc:postgresql://localhost:5432/nbhdb
    driverClassName: org.postgresql.Driver
    username: nbhdbadmin
    password: nbhdbadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /hosp-mgmt

logging.level:
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE