spring:
  application:
    name: Hospital Management Application
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2.console:
    enabled: true
    settings:
      web-allow-others: true

server:
  port: 8080
  servlet:
    context-path: /hosp-mgmt

logging.level:
  org.hibernate:
    SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE