package com.nkit.hospmgmtapp.exceptionhandler;

public interface ExceptionKey {
  String PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND";
  String PATIENT_GENDER_NOT_PROVIDED = "PATIENT_GENDER_NOT_PROVIDED";
  String PATIENT_FIRST_NAME_NOT_PROVIDED = "PATIENT_FIRST_NAME_NOT_PROVIDED";
  String PATIENT_LAST_NAME_NOT_PROVIDED = "PATIENT_LAST_NAME_NOT_PROVIDED";
  String PATIENT_DOB_NOT_PROVIDED = "PATIENT_DOB_NOT_PROVIDED";
  String PATIENT_MOBILE_NUMBER_NOT_PROVIDED = "PATIENT_MOBILE_NUMBER_NOT_PROVIDED";
  String PATIENT_EMAIL_ID_INVALID = "PATIENT_EMAIL_ID_INVALID";

  String DIALYSIS_SLOT_START_TIME_NOT_PROVIDED = "DIALYSIS_SLOT_START_TIME_NOT_PROVIDED";
  String DIALYSIS_SLOT_START_TIME_INVALID = "DIALYSIS_SLOT_START_TIME_INVALID";

  String DIALYSIS_SLOT_NAME_NOT_PROVIDED = "DIALYSIS_SLOT_NAME_NOT_PROVIDED";
  String DIALYSIS_SLOT_NAME_INVALID = "DIALYSIS_SLOT_NAME_INVALID";
}
