package com.nkit.hospmgmtapp.exceptionhandler;

public interface ExceptionKey {
  // Patient Error Keys
  String PATIENT_ID_NOT_PROVIDED = "PATIENT_ID_NOT_PROVIDED";
  String PATIENT_ID_INVALID = "PATIENT_ID_INVALID";

  String PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND";
  String PATIENT_GENDER_NOT_PROVIDED = "PATIENT_GENDER_NOT_PROVIDED";
  String PATIENT_FIRST_NAME_NOT_PROVIDED = "PATIENT_FIRST_NAME_NOT_PROVIDED";
  String PATIENT_LAST_NAME_NOT_PROVIDED = "PATIENT_LAST_NAME_NOT_PROVIDED";
  String PATIENT_DOB_NOT_PROVIDED = "PATIENT_DOB_NOT_PROVIDED";
  String PATIENT_MOBILE_NUMBER_NOT_PROVIDED = "PATIENT_MOBILE_NUMBER_NOT_PROVIDED";
  String PATIENT_EMAIL_ID_INVALID = "PATIENT_EMAIL_ID_INVALID";

  // Dialysis Station Error Keys
  String DIALYSIS_STATION_INVALID = "DIALYSIS_STATION_INVALID";
  String DIALYSIS_STATION_IS_NOT_AVAILABLE_FOR_DIALYSIS =
      "DIALYSIS_STATION_IS_NOT_AVAILABLE_FOR_DIALYSIS";

  // Dialysis Slot Error Keys
  String DIALYSIS_SLOT_START_TIME_NOT_PROVIDED = "DIALYSIS_SLOT_START_TIME_NOT_PROVIDED";
  String DIALYSIS_SLOT_START_TIME_INVALID = "DIALYSIS_SLOT_START_TIME_INVALID";

  String DIALYSIS_SLOT_NAME_NOT_PROVIDED = "DIALYSIS_SLOT_NAME_NOT_PROVIDED";
  String DIALYSIS_SLOT_NAME_INVALID = "DIALYSIS_SLOT_NAME_INVALID";

  // Dialysis Schedule Error Keys
  String DIALYSIS_SCHEDULE_DATE_NOT_PROVIDED = "DIALYSIS_SCHEDULE_DATE_NOT_PROVIDED";
  String DIALYSIS_ALREADY_SCHEDULED_FOR_THIS_PATIENT_ON_REQUESTED_DATE =
      "DIALYSIS_ALREADY_SCHEDULED_FOR_THIS_PATIENT_ON_REQUESTED_DATE";
  String NO_DIALYSIS_SCHEDULE_AVAILABLE = "NO_DIALYSIS_SCHEDULE_AVAILABLE";
  String NO_DIALYSIS_SCHEDULE_AVAILABLE_PER_REQUESTED_STATION_AND_SLOT =
      "NO_DIALYSIS_SCHEDULE_AVAILABLE_PER_REQUESTED_STATION_AND_SLOT";

  String DIALYSIS_SCHEDULE_STATUS_NOT_PROVIDED = "DIALYSIS_SCHEDULE_STATUS_NOT_PROVIDED";

  String DIALYSIS_SCHEDULE_NOT_FOUND = "DIALYSIS_SCHEDULE_NOT_FOUND";

  // Billing error keys
  String BILL_ITEMS_NOT_PROVIDED = "BILL_ITEMS_NOT_PROVIDED";
  String PAID_AMOUNT_IS_MORE_THAN_BILL = "PAID_AMOUNT_IS_MORE_THAN_BILL";
}
